### ISSUE TITLE
Better display on iPad

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#111]
Progress charts on iPad don't look nice because they are too large and should look like iPhone ones (set a max width for the container of the chart). 

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-04-10 at 09 45 59](https://user-images.githubusercontent.com/8709134/78975444-63abfe80-7b14-11ea-97f5-23482ebd156f.png)

**Comment by BatDroid** [comment]
I'm working on this
