### ISSUE TITLE
New color schema 

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#119]
Replace existing colors, e.g `Colors.linkGreen` by the new ones : 
<img width="953" alt="Screenshot 2020-04-14 at 12 48 22" src="https://user-images.githubusercontent.com/8709134/79216972-53668d00-7e4e-11ea-95df-f425d979f77b.png">
e.g `Colors.green80`

**Comment by kamal-kaur04** [comment]
Hii, can I take up this issue?

**Comment by PierreBresson** [comment]
Hello @kamal-kaur04 
Absolutely 🙂

**Comment by akkikumar72** [comment]
@PierreBresson I just saw the existing color schema, Looks like `Colors.linkGreen` matches to `Colors.green50` and we don't have any color like `color.green80` currently.
Should I just replace the existing color or add new colors(e.g color.green80) also?

**Comment by PierreBresson** [comment]
Yes, delete all current ones (linkGreen, darkLink...) and add the new ones.

**Comment by akkikumar72** [comment]
@PierreBresson PR for this fix - https://github.com/NMF-earth/nmf-app/pull/141

**Comment by PierreBresson** [comment]
@akkikumar72 merged, thanks for your contribution :)
