### ISSUE TITLE
Electricity emission

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#133]
Add electricity as an new emission type. User should be able to select a certain amount kWh from the slider and it should be calculated using user location https://github.com/NMF-earth/nmf-app/issues/132
Icon used should be md-flash

**Comment by akkikumar72** [comment]
@PierreBresson I was planning to contribute to this project. Should I start with this task or do we have any other task to start things up?

**Comment by PierreBresson** [comment]
@akkikumar72 yes you can grab this task, but it could be a bit complicated and long for a first issue. I've tagged some issues with the tag "Good first issue" if you want something smaller/easier.

Tomorrow afternoon I will do [issue 132](https://github.com/NMF-earth/nmf-app/issues/132) which is related to this issue (you need it to make this issue). 

I will do this task during the hackathon organized by hack for future (stockholm based but online because of corona). You can find more info at https://hackforfuture.org/

**Comment by akkikumar72** [comment]
@PierreBresson thanks for your prompt reply. It looks like [Issue-119](https://github.com/NMF-earth/nmf-app/issues/119) will be a good start. 
Hack for the future looks awesome. I really like taking part in the hackathon. I came 5th https://www.hackthecrisis.se/  and have taken pause after that.
