### ISSUE TITLE
Emission info

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#144]
Add a button on EmissionItemScreen opening a new modal screen. This new modal screen should show some text from a markdown file, in the same way as sustainable guide is working.

<img width="323" alt="Screenshot 2020-06-25 at 09 03 08" src="https://user-images.githubusercontent.com/8709134/85672332-1119c180-b6c3-11ea-8d04-5167d52e614f.png">

<img width="327" alt="Screenshot 2020-06-25 at 09 03 20" src="https://user-images.githubusercontent.com/8709134/85672341-124aee80-b6c3-11ea-9abd-84dcfbc863fb.png">

**Comment by akkikumar72** [comment]
What kind of markdown we have here. Are we using anything?

**Comment by PierreBresson** [comment]
Same markdown mechanism as act tab / sustainable guide.

**Comment by akkikumar72** [comment]
Looks like it same as https://github.com/NMF-earth/nmf-app/issues/154.
If yes, I can have a look

**Comment by PierreBresson** [comment]
> Looks like it same as #154.
> If yes, I can have a look

Exact, same as #154

**Comment by adamfitzgibbon** [comment]
I ended up grabbing this one since it was untouched for a while. It was pretty quick and easy thanks to the previous efforts!
