### ISSUE TITLE
fix: slow navigation on Android

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#148]
Transition between screen are slow on production apk. React navigation has been updated, from version 4 to 5 it's probably the reason.
To see the difference download current version on the google play and then install this [version after to compare](https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40nmf_earth/not-my-fault-earth-487ddd89ab624aada74b648c969c7e56-signed.apk).

**Comment by akkikumar72** [comment]
I can have a look at iPhone build, Can I get `. ipa` file for ios.

**Comment by PierreBresson** [comment]
@akkikumar72 Only affecting iPhone but you check the bug if you download Android Studio and then an android emulator.

**Comment by PierreBresson** [comment]
https://github.com/react-navigation/react-navigation/issues/7775
https://reactnavigation.org/docs/stack-navigator/#transitionpresets

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/nmf-app/pull/152
