### ISSUE TITLE
Methodology screen

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#154]
Add a screen accessible from the icon info from "Add new emission" explaining how emissions are calculated

<img width="178" alt="Screenshot 2020-08-23 at 20 57 47" src="https://user-images.githubusercontent.com/8709134/90986474-623f1800-e583-11ea-80f0-7379e48653a8.png">

**Comment by akkikumar72** [comment]
I can have a look at it.

**Comment by PierreBresson** [comment]
@akkikumar72 thanks, you can put some lorem ipsum text for now, I will correct it later ;)

**Comment by akkikumar72** [comment]
@PierreBresson - Created a PR for this feature

**Comment by PierreBresson** [comment]
Thanks a lot @akkikumar72 👏 !
