### ISSUE TITLE
Fix hooks warning

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#156]
Fix hooks warning in AddEmission screen :

![hooks](https://user-images.githubusercontent.com/8709134/91750558-96d65380-ebc3-11ea-8c2e-71e60aebb519.jpeg)

**Comment by pratyaksh123** [comment]
https://stackoverflow.com/questions/57397395/react-has-detected-a-change-in-the-order-of-hooks-but-hooks-seem-to-be-invoked
This might help, tho I can't see any wrong Component calls in AddEmission.tsx
