### ISSUE TITLE
expo icon on top on splashscreen

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#160]
See what's wrong with android build process : https://docs.expo.io/guides/splash-screens/
Maybe update expo will fix the issue

![signal-2020-09-11-161524](https://user-images.githubusercontent.com/8709134/92936192-1973d400-f44a-11ea-86ce-e397221d8ed9.jpeg)

**Comment by gurvanhenry** [comment]
Your `app.example.json` do not include de `"splash"` configuration.

I guess your app.json is different. 
Could you add your splash settings in the `app.example.json` file?

I tried with the following settings and did not reproduce your descrivbed issue (expo icon in front of splash image).

>     "splash": {
>       "image": "./assets/images/ios.icon.png",
>       "resizeMode": "contain",
>       "backgroundColor": "#000000"
>     },

**Comment by PierreBresson** [comment]
I've added the splash to [app.exmple.json](https://github.com/NMF-earth/nmf-app/commit/11d512a4a3891cb8d00e5d6d0615dccf82c522ae), let's hope it fix the bug, thanks :)
