### ISSUE TITLE
Methodology content

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#163]
Fill methodology screen with some content explaining how the carbon calculation is made (see https://github.com/NMF-earth/nmf-app/issues/154)

**Comment by sarthakpranesh** [comment]
Hey @PierreBresson, I would love to help with this issue. Can you please point me in the right direction for carbon emission calculation or is it required that the content be along the lines provided in #154 image

**Comment by PierreBresson** [comment]
@sarthakpranesh thanks for reaching out 🤗
I'm gonna take over this ticket because I realised now that the calculation might be a bit complicated to explain for the streaming and since I've implemented it, will be easier for me.
But feel free to grab this [issue](https://github.com/NMF-earth/nmf-app/issues/165) 🙂

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/nmf-app/commit/09f2fc01195b4fa397980d2558385e1fed189ad0
