### ISSUE TITLE
Update Expo to SDK 39

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#164]
More info : 

https://dev.to/expo/expo-sdk-39-is-now-available-1lm8

https://reactnative.dev/blog/2020/07/06/version-0.63

**Comment by pratyaksh123** [comment]
Hey, I can work on this, did you figure out the breaking changes?

**Comment by PierreBresson** [comment]
@pratyaksh123 thanks 🙂 
According to what I can see in the articles, there should be not major breaking changes (hopefully) and it should be pretty easy 🤗

**Comment by PierreBresson** [comment]
NB : due to spam, I won't assigned anyone to this very simple task. First PR up, first to merge, if correct.
