### ISSUE TITLE
Setup correctly eslint and prettier

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#165]
Using this [article](https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project)

Reason : seems maintainers have different formatting, resulting in many useless changes when a little change is introduced. See comma in [this commit](https://github.com/NMF-earth/nmf-app/commit/b8027f0cb5e70041651706863ff7a905b4ec572a) for example.

Let's have a solid and similar setup for everyone.

I don't think `"lint": "eslint --ext .js,.jsx,.ts,.tsx ./app",` from `package.json` need to be changed

_NB: at the moment, it's partially implemented_

**Comment by gurvanhenry** [comment]
Fun fact, few minutes ago I have just added this suggestion in my sticky note for you. 

I can handle that point if you want.
