### ISSUE TITLE
Custom Path Aliases

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#167]
Use custom path aliases thanks to `babel-plugin-module-resolver`. See last paragraph on this [page](https://reactnative.dev/docs/typescript).

E.g : in `About.screen.tsx` instead of 
```
import { Text, StickersImage } from "../../components";
```
It should be : 
```
import { Text, StickersImage } from "components";
```

NB: this ticket is not about implementing this in all the screens, this can be done later in another issue. This is just to put the mechanism in place.

**Comment by geraldobraz** [comment]
I would like to take this.

**Comment by laurameck** [comment]
Hey, I'd like to work on this. Can you assign it to me?

**Comment by PierreBresson** [comment]
@laurameck done, you are assigned ;)
