### ISSUE TITLE
Re-organize imports on save

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#172]
Would be nice to have something clean like this : 
```
import React from 'react';

import { PropTypes } from 'prop-types';
import styled from 'styled-components/native';

import ErrorImg from '../../assets/images/error.png';
import colors from '../../styles/colors';
```
See this [article](https://dev.to/otamnitram/sorting-your-imports-correctly-in-react-213m) for more info

**Comment by aneeshrelan** [comment]
Can I take this up?

**Comment by mrpmohiburrahman** [comment]
@PierreBresson hey, I'd like to work on this. Can you assign it to me?

**Comment by kajal1122** [comment]
assign this to me

**Comment by PierreBresson** [comment]
Due to spam, I won't assigned anyone to this very simple task. First PR up, first to merge, if correct.

**Comment by stijnbernards** [comment]
See https://github.com/NMF-earth/nmf-app/pull/181

**Comment by PierreBresson** [comment]
@stijnbernards seems like saving file doesn't re-organise anything for me. And also want the imports sorted in alphabetical order (for anything except for 'react' & co who should be on top)

**Comment by stijnbernards** [comment]
@PierreBresson This should be handled by your editor settings. Do you use eslint/prettier?

**Comment by PierreBresson** [comment]
@stijnbernards the idea is that you don't need to change any settings yourself and that format on save should come from `.vscode/settings.json` so we all have the same behavior when saving file. For some reason, now it's working on my computer. However I have the following issue : 

On top of BudgetScreen.tsx, I have : 

```
import React from "react";
import { ScrollView } from "react-native";
import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";
```

If I change it to the following : 
```
import React from "react";
import { ScrollView } from "react-native";

import styles from "./BudgetScreen.styles";
import { useSelector } from "react-redux";
import { Text, Button } from "../../components";
```

And save the file, I get the following : 

```
import React from "react";
import { ScrollView } from "react-native";

import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";
```

Instead of : 
```
import React from "react";
import { ScrollView } from "react-native";
import { useSelector } from "react-redux";

import styles from "./BudgetScreen.styles";
import { Text, Button } from "../../components";
```

Any idea why ?

**Comment by hb2708** [comment]
@PierreBresson If i put all of the part in .eslintrc.js as per doc that works as expected.

**Comment by hb2708** [comment]
@PierreBresson created a pr but the linter will fails. Added comments on the pr. So once you come back. Can check and decide.
