### ISSUE TITLE
Clean dependencies in package.json

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#174]
Some packages are in dependencies instead of devDependencies such as typescript.

**Task:** going through all dependencies and move unnecessary ones in order to decrease app size 🌱

_NB : due to spam, I won't assigned anyone to this very simple task. First PR up, first to merge, if correct._

**Comment by abhisht51** [comment]
But how do I figure out the ```unnecessary``` ones?

**Comment by PierreBresson** [comment]
@abhisht51 Hello,
You can knwo that thanksto your experience or by looking at the code. For example, you won't see any `import { } from 'typescript'`

**Comment by mahmoodhosseini** [comment]
Are you going to keep both `yarn.lock` and `package-lock.json`?

**Comment by iraj465** [comment]
Hi @PierreBresson !
Please check my PR.
Thanks.

**Comment by maxsynnott** [comment]
Hey @PierreBresson,
Hope this was helpful.
