### ISSUE TITLE
Custom Path Aliases Part 2

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#177]
Following #167 

Replace the following direct path of `ducks, interface, components, utils, navigation, style`

So the following : 

``` 
import { emissions } from "../../../ducks";
import { Emission } from "../../../interfaces";
import { calculation, ui } from "../../../utils";
import { Text, Button, StickersImage } from "../../components";
import { Colors, ComponentsStyle } from "../../style";
import { navigate } from "../../navigation";
```

Should be transformed into : 

```
import { emissions } from "ducks";
import { Emission } from "interfaces";
import { calculation, ui } from "utils";
import { Text, Button, StickersImage } from "components";
import { Colors, ComponentsStyle } from "style";
import { navigate } from "navigation";
```

_NB1 : Will affect a lot of files but it's an easy task
NB2 : due to spam, I won't assigned this task to anyone without previous contribution to this repo but PR are accepted, just have a look if there is no PR up and if this issue is not assigned to anyone._

**Comment by stijnbernards** [comment]
WIP in: https://github.com/NMF-earth/nmf-app/pull/188

**Comment by stijnbernards** [comment]
Resolved 😁

**Comment by hb2708** [comment]
@PierreBresson  Still open?

**Comment by PierreBresson** [comment]
@hb2708 yes, @stijnbernards started it but never finished it.

**Comment by hb2708** [comment]
ok @PierreBresson let me give a try. 

It's sad that you removed the `hacktoberfest` tag already. Or else This could have been my 4th and last pr For the Event.
