### ISSUE TITLE
Improve constants import

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#178]
Instead of : 

```
import { isSmallDevice } from "../../constants/Layout";
import ImagesAssets from "../../constants/ImagesAssets";
import { currentTermsOfUseVersion } from "../../constants/Preferences";
```

We should have : 

```
import { Layout, ImagesAssets, Preferences } from "constants";
```

And change the code to the following : 

```
Layout.isSmallDevice
Preferences.currentTermsOfUseVersion
ImagesAssets.stickers.earth
```
etc

In order to not have `import { } from "../../constants"` but `import { } from "constants"`, take advantages of this  #167 

_NB1 : Will affect many files but it's an easy task
NB2 : due to spam, I won't assigned this task to anyone without previous contribution to this repo but PR are accepted, just have a look if there is no PR up and if this issue is not assigned to anyone_

**Comment by evayde** [comment]
@PierreBresson `constants` is a NodeJS Type, hence I guess we might not be able to use it here. Should it be renamed to `constant` or do you have another solution?

**Comment by PierreBresson** [comment]
> @PierreBresson `constants` is a NodeJS Type, hence I guess we might not be able to use it here. Should it be renamed to `constant` or do you have another solution?

Oups, my bad, yes renamed constant ☺️

**Comment by PierreBresson** [comment]
@evayde Looks like there is a little problem on ios `Unable to resolve "constant" from "app/screens/Emissions/components/SectionHeader/SectionHeader.styles.ts"`

**Comment by evayde** [comment]
Looking into it

**Comment by evayde** [comment]
Hey @PierreBresson 
I am on commit 0d6e28af650c497366746ff62bc921df975fcb89 (HEAD -> master, upstream/master)
I also removed node_modules and even repulled the whole repository. I cannot see this error.

I am debugging on iOS 14, iPhone SE2 simulator.

Node Version: 14.4.0
npm Version: 6.14.5

I have also looked into the component itself and cannot see anything out of the usual.
Any hints? Or did you already solve it?

**Comment by PierreBresson** [comment]
@evayde today it's working (I've restarted my computer but didn't change anything / still on master) so it's strange. Maybe a caching issue related to https://github.com/NMF-earth/nmf-app/issues/187. Closing for now, thanks for the pr 🤗
