### ISSUE TITLE
Emission input by setting a value

### ISSUE THREAD

**Issue by zonArt** [NMF-earth/nmf-app#180]
Hi,

I've just discovered this app and wondered if it could be an idea to give the possibility to the user to enter the value of the emission (will it be food, travel or any other) by entering it on the keyboard. I'm saying that because to get it right with the slider is nearly impossible. I'd love to contribute by submitting a PR in the context of Hacktoberfest but know nothing on typescript neither on the internal structure of your code. Any starting point input would be highly appreciated. Thank you very much

**Comment by PierreBresson** [comment]
Hi @zonArt 

It's indeed a feature we want to develop in the next version.

Here is a look of the design of the component : 

<img width="495" alt="Screenshot 2020-10-06 at 17 10 45" src="https://user-images.githubusercontent.com/8709134/95220627-f3e2ac00-07f6-11eb-8d3c-162d8abd2f66.png">

<img width="210" alt="Screenshot 2020-10-06 at 17 10 59" src="https://user-images.githubusercontent.com/8709134/95220634-f47b4280-07f6-11eb-84c1-32adad60759e.png">

Try to have a look to other components to see the best practices. Note that this component needs to support all the inputs needed (distance, weight...)

If it's a too big/complicated task for you, I've tried to make some small issues so you can also participate
