### ISSUE TITLE
Operator 'abs' not found

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#185]
Fix following error when running app from master : 

<img width="596" alt="Screenshot 2020-10-07 at 11 25 52" src="https://user-images.githubusercontent.com/8709134/95313085-0230d680-0890-11eb-82e8-fea9effc6399.png">

**Comment by evayde** [comment]
Hello, I would like to fix this. I did run the app from master on iOS, but the Error didn't show up. Anything special we have to do in order to reproduce it?

**Comment by PierreBresson** [comment]
Hi @evayde 
Did you run `git pull` and `yarn` after?

**Comment by evayde** [comment]
@PierreBresson 
Hey Pierre,
I just forked the repo today, then cloned it, followed the readme to copy files, installed deps with `yarn`, and ran `yarn ios`. 
I can use the app normally.

![image](https://user-images.githubusercontent.com/25255815/95375662-359b5180-08e0-11eb-8376-e5ae36e742c5.png)

**Comment by PierreBresson** [comment]
@evayde yes but today expo was updated. Anyway I've fixed it in https://github.com/NMF-earth/nmf-app/commit/947d33b02abc9313aed37a094f1a891432049a55
