### ISSUE TITLE
German translation imports the wrong file

### ISSUE THREAD

**Issue by evayde** [NMF-earth/nmf-app#189]
`app/screen/Budget/translations/index.ts`

imports the `en.json` twice, which results in a linter warning. The import for the german file is wrong:

```
import en from "./en.json";
...
import de from "./en.json";
```

**Comment by PierreBresson** [comment]
@evayde [fixed](https://github.com/NMF-earth/nmf-app/commit/ddcafde82d3d0741aaa3bf287ba005dab3596591), thanks
