### ISSUE TITLE
Tab bar text needs margin

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#191]
Tab bar in the bottom of the screen needs to be improved : the text is too close to the OS navigation/controls. Instead we should have at least 4px of margin, between act and the bottom for e.g

![signal-2020-10-09-122323](https://user-images.githubusercontent.com/8709134/95573037-2543bd80-0a2b-11eb-97ed-3e2e5799d265.jpeg)

**Comment by BatDroid** [comment]
what is the status here. can i do it?

**Comment by PierreBresson** [comment]
Seems like it got [stucked](https://github.com/NMF-earth/nmf-app/pull/192). Yeap 👍
