### ISSUE TITLE
Export / Import data

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#206]
Since the app doesn't rely on any backend, if a user looses its phone, all data is gone. To solve this issue, let's add a manual save mechanism.

In settings, add two row : 

- Export data : this should trigger a function that will grab all user emissions from the redux store and store it in a `.json` file (or similar) that the user can save where he wants on his phone.

- Import data : this will ask user to select the `.json` file previously exported in order to replace `emissions` in the redux state with the data in the file.

_NB1 : this is could be a large and complicated task, probably not suitable for beginners._
_NB2 : due to spam, I won't assigned this task to anyone without previous contribution to this repo but PR are accepted, just have a look if there is no PR up and if this issue is not assigned to anyone._

<img width="375" alt="settings" src="https://user-images.githubusercontent.com/8709134/95775311-77524080-0cc2-11eb-9412-8a63ce8cf534.png">

**Comment by adamfitzgibbon** [comment]
I'm going to take a crack at this one.

**Comment by adamfitzgibbon** [comment]
Although thinking about this solution a bit, I'm not sure having a static file would be that useful to the user. They'd basically have to constantly save the backup file to a separate device to be protected. I know on iPhone apps can backup data in icloud and I would assume there's something similar for Android. Would doing something like that be a little bit more useful?

**Comment by PierreBresson** [comment]
Let's try to make small issues so importing/exporting a static file is the first step.

Maybe later : 

We could have an another screen after pressing on import/export data showing the following : 
if(ios) 
- allow to save data on icloud 
- export data on static file

if(android) 
- allow to save data on google Drive 
- export data on static file

A lot of users have icloud/drive, but is it always the case? Does having appleID means that you get icloud storage? (same question for google drive).


We decide that dropbox is less toxic compare to apple/google and will make our life easier (one service to implement instead of two). But not all user have dropbox and this company is clearly not on the rise so is it worth investing time on something that is slowly dying...


We find an open source alternative to dropbox (webDav? see buttercup)


[Buttercup](https://github.com/buttercup/buttercup-mobile) is proposing file saving and I have no complain with that system so far.

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/nmf-app/pull/263
