### ISSUE TITLE
Notifications (Stickerd Reward 🎁)

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#213]
Allow user to receive a notification every Sunday at 9 p.m to reminding him to add emissions.

Not activated by default (ethic / privacy / good patern).

_NB1 : this is could be a large and complicated task, probably not suitable for beginners.
NB2 : due to spam, I won't assigned this task to anyone without previous contribution to this repo but PR are accepted, just have a look if there is no PR up and if this issue is not assigned to anyone._

**Reward** : I will be sending stickers (from the [kickstarter](https://www.kickstarter.com/projects/pierrebresson/not-my-fault?ref=nav_search&result=project&term=not%20my%20fault)) by mail to the person doing this PR, for free, because it's a feature claimed by several people 🙂

<img width="482" alt="Screenshot 2020-10-16 at 14 05 14" src="https://user-images.githubusercontent.com/8709134/96256329-bb8e5b00-0fb8-11eb-9303-28227adadcb5.png">

**Comment by BatDroid** [comment]
I'm gonna start working on it

**Comment by BatDroid** [comment]
@PierreBresson 
I've implemented the IOS part but as you can see [here](https://docs.expo.io/versions/latest/sdk/notifications/#calendarnotificationtrigger) [here], it is not supported for android yet. shall i add it just for ios devices?
if yes have you considered any title and description for the notification?

**Comment by PierreBresson** [comment]
Yes, let's do the android later then, thanks. I was thinking of something like :
Title : Weekly Emissions 🗓
Description: Here is a kindly reminder to add your emissions for this week.
