### ISSUE TITLE
Design breaking for "Change" action

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#214]
Put "Change" on a another line below the date
![Simulator Screen Shot - iPhone 4s - 2020-10-14 at 23 31 55](https://user-images.githubusercontent.com/8709134/96262341-f34dd080-0fc1-11eb-89f0-082170e8eeaa.png)

**Comment by adamfitzgibbon** [comment]
Sorry, I didn't correctly link the issue so this didn't get closed when my PR got merged. This can be closed now.
