### ISSUE TITLE
Fix little bug in a guide script

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#239]
**Describe the bug**

Remove "personal" path (`/Users/pierrebresson/Documents/Git/nmf-app/assets//markdown/`) in snapshot file (like it was before). See `key` in this hot [fix](https://github.com/NMF-earth/nmf-app/commit/a32dc9adc900803964ec7964d299d04a6a9a87f1)

This is a side effect of using `${process.env.PWD}` in order to make the script work (see issue #199 )

**Comment by hb2708** [comment]
@PierreBresson How can i run the test locally.
I tried all from this section but it seems like that is not the one. 
https://github.com/NMF-earth/nmf-app#-testing

As i think it should fail on all others machine expect urs as the file contains ur local path
`app/screens/Act/__tests__/__snapshots__/ActScreen.test.tsx.snap`

Let me know your thoughts here.

**Comment by PierreBresson** [comment]
@hb2708 I'm not refering to the tests (__snapshots__) but to the [sutainable guide scripts](__snapshots__) : `node scripts/generate-guides.js`

**Comment by hb2708** [comment]
> **Describe the bug**
> 
> Remove "personal" path (`/Users/pierrebresson/Documents/Git/nmf-app/assets//markdown/`) in snapshot file (like it was before). See `key` in this hot [fix](https://github.com/NMF-earth/nmf-app/commit/a32dc9adc900803964ec7964d299d04a6a9a87f1)
> 
> This is a side effect of using `${process.env.PWD}` in order to make the script work (see issue #199 )

This say the other way around. i thought the change in `scripts/generate-guides.js` is acceptable. Coz that makes it work on all the machines

**Comment by PierreBresson** [comment]
@hb2708 yes you can run then and they work but next time someone else than me run the guide script the following path will change : `/Users/pierrebresson/Documents/Git/nmf-app/assets//markdown/`
it's bad praticse to have this kind of path `users/xxx`

**Comment by hb2708** [comment]
@PierreBresson not sure if I missed to check it properly but can you tell me how i can create new snapshots based on guide? Coz when i run it had your path and still works nicely

**Comment by hb2708** [comment]
@PierreBresson So I figured the way to regenerate new snapshots. And made some changes to generate-guides.js. Take a look and see if that works for you. I did test locally and testes were green
