### ISSUE TITLE
master -> main

### ISSUE THREAD

**Issue by a2br** [NMF-earth/nmf-app#243]
Hey, According to Git's norms, main branches should be named `master`, and according to GitHub's norms, they should be named `main` (for ethical concerns). What do you think about renaming the `master` branch here?
These CLI commands are all it takes.
```console
git checkout master
git branch -m main
git push origin -u main
git push origin --delete master
```

**Comment by PierreBresson** [comment]
Thanks for bringing that subject, I was planning to do it but forgot. Now it's done 🤗
