### ISSUE TITLE
Update expo

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#250]
Update expo to [sdk 40](https://dev.to/expo/expo-sdk-40-is-now-available-1in0)

**Comment by petruspierre** [comment]
Hey

Everything is working, we just need to decide a point. In the new version of the SDK it asks us to use `@expo/vector-icons` in version `^12.0.0` (currently we use `10.0.6`).

If we did the update, we will have to update several icons that have changed their name or have been changed in Ionicons. (e.g. `md-stats` is now `md-stats-chart`)

The project still works using version 10.0.6, however, we will receive a warning every time when running `expo start`.

So should we leave it in the current version and open another Issue to solve the icons separately?

**Comment by PierreBresson** [comment]
Hello @petruspierre 

As you want, if you want to update the icons you can do it in the same PR as the expo update, it shouldn't take long. Otherwise yes, it would be nice to have an issue to update the icons separately.
