### ISSUE TITLE
Fix test issues with jest and dates

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#294]
- [ ] Currently tests need to be updated everyday because the date change in the snapshots, see [this example](https://github.com/NMF-earth/nmf-app/commit/0ea649b277ccb818f1932a10566c7bbc2a997cdb). 
- [ ] There are issues with `yarn test` for some people, see [pr292](https://github.com/NMF-earth/nmf-app/pull/292#discussion_r682418148).

**Comment by BatDroid** [comment]
should we apply all the changes in PR for that?

**Comment by PierreBresson** [comment]
@BatDroid What do you mean exactly?

**Comment by BatDroid** [comment]
nothing. I guess I didn't see that You've merged the PR. 
shall I give it a try?

**Comment by BatDroid** [comment]
@PierreBresson Do you mind if I use [this](https://github.com/boblauer/MockDate). I tested many things but a boilerplate code was the only way. I either can use the ugly boilerplate or use the mentioned package (which almost [does the same thing](https://github.com/boblauer/MockDate/blob/master/src/mockdate.ts)). after all, it'll be in dev dependency. Give me an ok & consider it done :)

**Comment by BatDroid** [comment]
Also, I can add this [workaround](https://github.com/nodejs/node/issues/4230#issuecomment-480749039) for the other issue. do you approve it?

**Comment by PierreBresson** [comment]
Yeap, the workaround and the MockDate sound good to me 👍
