### ISSUE TITLE
Add emission in tab bar

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#296]
#### Summary
Add emission should be in the tab bar for quicker access and the button "Add emission" should be removed from emissions screen

![tabSelected=Add](https://user-images.githubusercontent.com/8709134/128757407-b45f780f-2d14-4e6b-972d-f415730ef370.png)

**Comment by Michelalmeidasilva** [comment]
Hello brother, i'm working on this at moment and i have some images to show. 
I removed the add emission button from emission screen and i added a new tab into bottom navigator.  

![image](https://user-images.githubusercontent.com/37683337/129842758-4d000d88-3cdb-430f-b750-f9a142b923f2.png)

![image](https://user-images.githubusercontent.com/37683337/129842771-402fd2e4-9810-4418-b210-1800e2074f26.png)

**Comment by PierreBresson** [comment]
Hello @Michelalmeidasilva and thanks for having a look to this issue 🙂
Except the back button on the second image, it looks good to me 👍

**Comment by PierreBresson** [comment]
Done in https://github.com/NMF-earth/nmf-app/pull/304 and https://github.com/NMF-earth/nmf-app/commit/94808a45fa94f59a18849905fc10234ececb8790
