### ISSUE TITLE
Fix Github Actions

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#298]
**Describe the bug**
Fix [github actions](https://github.com/NMF-earth/nmf-app/runs/3343523159?check_suite_focus=true)

**Comment by BatDroid** [comment]
I was just about going to go to bed with my "10% brain functionality"  & saw this & couldn't leave it for later. so there's a high chance that it does nothing. so, sorry in advance if it didn't work :)

**Comment by PierreBresson** [comment]
The "10% brain functionality" did a good job 🤗
Thanks!
