### ISSUE TITLE
chore: update expo-file-system

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#301]
- [ ] update `expo-file-system` to latest. Currently it's `11.0.2` version since I had issues with version `11.1.3` see #295 
- [ ] make sure that importing a json file with saved data is working on both android and ios

_NB: First to submit a valid PR, first to merge. Except if you already have merged some good code in this repo, I won’t assign any issue due to spam and beginners unable to complete a PR without a lot of help from my side._

**Comment by hb2708** [comment]
@PierreBresson This PR https://github.com/NMF-earth/nmf-app/pull/344 should do the job 🤞
