### ISSUE TITLE
Add 166 kg CO2 information source

### ISSUE THREAD

**Issue by jonatasbaldin** [NMF-earth/nmf-app#308]
Hi there!

First, thanks a lot for this app 🌱

#### Summary
Could we have a info button linking to the source of the 166 kg CO2 budget under the Paris agreement? I couldn't find any link with that info.

**Comment by PierreBresson** [comment]
Hello @jonatasbaldin and thank you for the feedback. It's indeed something we should clarify with a little "i" circle, like the one just above in the monthly budget screen.
You will probably never seen the 166 kg figure anywhere, but you might have seen the 2 tons of co2eq per capita per year by 2050 (166,66kg x 12 = 2 tons, bad rounding maybe we should fix that ^^). Or at least it's all over the news in France, like in [Carbon 4](https://www.carbone4.com/wp-content/uploads/2019/06/Publication-Carbone-4-Faire-sa-part-pouvoir-responsabilite-climat.pdf) think tank : 
"L’empreinte carbone moyenne des Français, qui s’élevait à 10,8 tonnes de CO2 en 2017, doit baisser d’environ 80% d’ici 2050 pour parvenir aux **2 tonnes de CO2 par an** compatibles avec l’Accord de Paris."

**Comment by jonatasbaldin** [comment]
Thanks @PierreBresson!

I found this thing called "Under2 Coalition", I believe it is the official name of the under 2 tonnes of co2eq/per year/per capita (https://en.wikipedia.org/wiki/Under2_Coalition).

I also think the wording could be something like: "Under 2 tonnes per year per capita (167kg per month)", just to be more explicit heh

**Comment by PierreBresson** [comment]
Indeed, that would be better 👍

**Comment by PierreBresson** [comment]
https://github.com/NMF-earth/nmf-app/commit/e6304c7fbc21f0fa492f9158d8cfd37efecf4ad0
