### ISSUE TITLE
New colors

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#313]
#### Summary
Bring all the colors of the [design file](https://www.figma.com/file/YS0Sa7XCzvnu6bpdogTN81/Earth-Design-System?node-id=4%3A2) in the app (see `Colors.ts`) and apply them in the different screens according to the [design file](https://www.figma.com/file/YS0Sa7XCzvnu6bpdogTN81/Earth-Design-System?node-id=40%3A0).

**Comment by PierreBresson** [comment]
Indeed, that's correct, pick colors from design file and replace colors with these new values. Then put these new colors everywhere in the app according to design file. Yeap, you can submit you pr anytime and then I will make sure to wait and merge it only the 1st of october so it counts for the event

**Comment by Divyateja04** [comment]
1. Also um can you give a sample as to how I replace colors in the app....like already some existing colors are there right?
2. Also I knowledge about react but not much about react-native so can you tell me how to run the app to test it

**Comment by PierreBresson** [comment]
@Divyateja04 Sorry but this is a RN app and therefore you need some knowledge about RN to contribute to this repository.

**Comment by Divyateja04** [comment]
Oh it's okay

**Comment by mtalhabaig3** [comment]
@PierreBresson can i do it?

**Comment by PierreBresson** [comment]
Sure ;)

**Comment by mtalhabaig3** [comment]
Alright! I am at it!

**Comment by mtalhabaig3** [comment]
@PierreBresson should i name the colors as in the design file or as in the code, for example in the design file its primary and in the code its green. Kindly guide me 🙂

**Comment by PierreBresson** [comment]
@mtalhabaig3 well done, thanks a lot, it's merged 🙂

**Comment by mtalhabaig3** [comment]
@PierreBresson no Problem 😊
