### ISSUE TITLE
Allow camera permission screen

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#318]
- [x] create the Allow camera permission screen
- [x] when clicking on Allow button, user should be presented the permission popup and if he has deny that, settings of the phone should be open, preferably settings page of NMF.earth
- [x] make sure that component re render on focus to detect any change in the settings

![134519189-44f33eaf-1133-479c-82fb-799d63045fde](https://user-images.githubusercontent.com/8709134/134642231-2849f521-98e5-4e67-8040-0f21f855789a.png)

**Comment by hb2708** [comment]
@PierreBresson does this ticket aim to have a redesign for the existing screen / flow??

![image](https://user-images.githubusercontent.com/13498448/139553662-9d0501e9-9500-46fb-b0df-bd3668dc0321.png)

**Comment by PierreBresson** [comment]
@hb2708 good question, humm no, let's keep it like that for now. However, I have experience that the component doesn't detect that settings have been change so we need to fix that. I've added a new line in the description
