### ISSUE TITLE
Storybook for NoEmission

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#32]
Create storybook for NoEmission component

**Comment by gurvanhenry** [comment]
I started this :

<img width="1393" alt="Screenshot 2020-09-30 at 15 10 07" src="https://user-images.githubusercontent.com/2821522/94689491-386dd380-032f-11eb-9abf-a011ec1291f8.png">

But it's really basic. (once I found the hidden storybook button 😋)
Can you be more precise on what you want on that point?

**Comment by PierreBresson** [comment]
@gurvanhenry thanks for having a look!
The idea is to have all the components is the storybook so the designers can have a look to them without having to put the app in a special state, in this case delete all the emissions of the app.
