### ISSUE TITLE
Periodicity screen

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#322]
- [x] create screen
- [x] display ClickableTags components see #324
- [x] return user input values to Add Emission screen when user press confirm / or store input values in redux

_NB: First to submit a valid PR, first to merge. Except if you already have merged some good code in this repo, I won’t assign any issue due to spam and beginners unable to complete a PR without a lot of help from my side._

![Periodicity](https://user-images.githubusercontent.com/8709134/134548575-4e378452-c06a-4d7a-b21b-e4ec215c47dc.png)
![Selected-1](https://user-images.githubusercontent.com/8709134/134548579-97417a1a-9755-4cbe-aac1-b37ffeb790fc.png)
![Selected](https://user-images.githubusercontent.com/8709134/134548580-f29c39f1-0e02-4bc4-9665-d9684b8d968f.png)

**Comment by PierreBresson** [comment]
Not really, #254 is just the listing of all the issues needed to complete the feature periodicity. Some work was done in #329 but it needs to be refactored into a component. 
Yes, clicking on `Non-recurring` in #254 is opening this periodicity screen

**Comment by BatDroid** [comment]
@PierreBresson I see, Then feel free to assign #315 & #321 to me as well.
