### ISSUE TITLE
Improved storybook

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#35]
We can improve our storybook by letting the user change the props instead of create a long list.
Now : 
<img width="518" alt="Screenshot 2020-01-05 at 15 19 56" src="https://user-images.githubusercontent.com/8709134/71781432-27c24400-2fcf-11ea-906c-6eb92e399965.png">
Better : 
Only two items in tag stories : no icon and with icon

**Comment by akkikumar72** [comment]
@PierreBresson Mind explaining a bit more about this task. Is it only for mobile?

**Comment by PierreBresson** [comment]
@akkikumar72 if you take EmissionListItem for example, the idea is to have one element instead of plane/build/restaurant. Instead, let's use toggle (or similar like checkbox) to display the what we wait.
Like this :
![66052628-35c87a80-e531-11e9-9110-18b5bc99effa](https://user-images.githubusercontent.com/8709134/84868047-5d8a4f00-b07c-11ea-86df-d7b421b8ede2.png)

**Comment by akkikumar72** [comment]
Sure, I will take care of it then.

**Comment by akkikumar72** [comment]
https://github.com/NMF-earth/nmf-app/pull/146
Added a draft PR, just check if I am on right track or not.
@PierreBresson

**Comment by PierreBresson** [comment]
@akkikumar72 Thanks, I think you are close to what I had in mind. Could you make the knobs available on the phone (cf screenshot in my previous comment)? 

The idea is to have the knobs on the phone so Anthony, and others designers, can have a look to the different rendering of the components in any state, on the phone directly, without having to yarn / install anything on the computer.

**Comment by akkikumar72** [comment]
Possible to raise PR from this repository. I guess need some more permissions then

**Comment by akkikumar72** [comment]
PR - https://github.com/NMF-earth/nmf-app/pull/149

**Comment by PierreBresson** [comment]
@akkikumar72 Excellent work, thanks 👌🏼
