### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#355]
#### Summary
Make sure that the FAQ on the website/app match

**Comment by mtalhabaig3** [comment]
@PierreBresson can give me the link of the website?

**Comment by PierreBresson** [comment]
Hi Muhammad,
Here it is : https://nmf.earth/about.html

**Comment by mtalhabaig3** [comment]
@PierreBresson thank you!

**Comment by mtalhabaig3** [comment]
@PierreBresson there some FAQs which are present in the app and not on the website and vice versa. Should i just include the FAQs which are missing in the app? Also some FAQs in the website are not questions just plain sentence, so should i make a question by myself? kindly guide.

**Comment by PierreBresson** [comment]
Hello @mtalhabaig3 
True that, it's a mess. I've prepared and update the FAQ for you [here](https://gist.github.com/PierreBresson/8fb901a32d2b70c8017f137ec21fdee4).
Just delete the current faq strings in all languages, I will add the new translations files in poeditor once the PR is merged ;)

**Comment by mtalhabaig3** [comment]
Alright @PierreBresson  I am working on it.
