### ISSUE TITLE
Enhancement: Improve slider handling for amounts

### ISSUE THREAD

**Issue by DGrothe-PhD** [NMF-earth/nmf-app#378]
#### Summary
As a user, I might take an occasional 5-km ride or buy some 100 or 125 grams of chocolate, etc.
However, I currently observe that 

- the closest to those 100 grams of chocolate is 97g, 113 g or something of that kind
- Fun fact on the other hand: I was able to jot down exactly 20 grams of red meat that seems to work better but I don't know why.
  So far I cannot figure out what dictates these ticks after all &hellip;
- the smallest distance I can enter by sliding is 2 km for a ride, next tick appears to be at 55 km
- and with further practice, I might be lucky to add 17 km, again far from the 5 km I was trying to enter.

#### Proposed feature
- The slider for entering metric amounts should have some more practical ticks and/or
- **Preferredly:** Being able to **tap on the number** above the slide and this opens a (standard) keyboard for entering a number.

Maybe such a number field is standard one with some accessibility improvement for some challenged people

#### To Do List 
- [ ] Code
- [ ] Tests
- [ ] README.md updated

**Comment by PierreBresson** [comment]
@DGrothe-PhD : thanks for the feedback, that's correct, it's not handy, so I've designed a solution for this problem. You can find [the proposal here](https://github.com/NMF-earth/nmf-app/issues/356).
