### ISSUE TITLE
Bug: Open Food database CO2eq overridden by 200kg after adding scanned emission

### ISSUE THREAD

**Issue by DGrothe-PhD** [NMF-earth/nmf-app#379]
**Describe the bug**
Scanned product is stored as having 200kg CO2eq instead of its actual value.

**To Reproduce**
1. Go to Add Emission &rightarrow; Scan Product
2. Scan a product which has a CO2eq value in Open Foods Database
3. Confirm that the slider appears to set item count (preset: 1 item) and there is a CO2eq value (usually below 10 kg) shown.
4. Press the `Add emission` button
5. Check the monthly emission screen and look at the item just stored

**Expected behaviour**
On monthly emission screen, an amount of CO2 for a food item taken from Open Foods Database should show the correct value.

**Screenshots**
Please find below.

** Please complete the following information (if applicable):**
 - Device: iPhone 12]
 - OS: iOS 16.5
 - Version 0.10.0-50

** Product screenshots**
for easily retrying
![cocomilk](https://github.com/NMF-earth/nmf-app/assets/64636863/ade4a680-4af7-430f-a2f5-22ebb2fcb077)
![peanutbutter_front](https://github.com/NMF-earth/nmf-app/assets/64636863/32d00950-2b11-4c96-b814-2296b3930470)
![peanutbutter_EAN](https://github.com/NMF-earth/nmf-app/assets/64636863/ae87be64-630c-4a5f-8eb3-ba85c3777b3a)

** Scanning process**
![scanning_cashew_cranberry_mix](https://github.com/NMF-earth/nmf-app/assets/64636863/5d0dee6c-957c-490c-a1c1-1339e18ef8b0)
![scanning_coco](https://github.com/NMF-earth/nmf-app/assets/64636863/e9c6a3c0-ab4b-45ef-8cdb-3831bddbd189)
![scanning_peanut](https://github.com/NMF-earth/nmf-app/assets/64636863/d42f6e43-c56e-4163-8216-a72ea0fee4d9)
And afterwards:
![EmissionsScreen_with3](https://github.com/NMF-earth/nmf-app/assets/64636863/957d1072-e273-4069-af84-70b894f5b7bc)

**Additional context**
(I was trying to debug but had couple of yarn issues so had to skip this.)

**Comment by saurabhchatterjee23** [comment]
https://github.com/NMF-earth/nmf-app/pull/386 fixed the issue in this PR
