### ISSUE TITLE
Arabic

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#383]
#### Summary
Add arabic language from [poeditor](https://poeditor.com/projects/po_edit?id_language=7&per_page=20&id=324389).

- [ ] Code
- [ ] Tests

**Comment by rosywisteria** [comment]
Hi Pierre I'd like to try this issue out!

**Comment by MunishMummadi** [comment]
I would like to word on this project.

**Comment by EugenSong** [comment]
hi Pierre. I'm not able to join nmf's poeditor translation group so that I can export Arabic's translation. 
Get the following error:
"This project can't accept new contributors at this time. Please try again later."

**Comment by PierreBresson** [comment]
Hi @EugenSong,
Must be an error from poeditor, I've created a gist for you : https://gist.github.com/PierreBresson/6b819d72133d789b98c3091cf1306eb3
