### ISSUE TITLE
Animated Splash Screens

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#50]
[Documentation](https://docs.expo.io/versions/latest/sdk/splash-screen/) 
Example [here](https://snack.expo.io/@bacon/animated-splash-screen) and [here](https://twitter.com/Baconbrix/status/1218637024875270146?s=20)

**Comment by devanshujain95** [comment]
@PierreBresson I have tried to create an animated splash. Check PR: #[138](https://github.com/NMF-earth/nmf-app/pull/138/files).

Removed splash key from app.json and added new component for Splash.

Let me know if any changes needed.

**Comment by devanshujain95** [comment]
@PierreBresson  Created new PR due to some glitches. Have a [look](https://github.com/NMF-earth/nmf-app/pull/140).

**Comment by PierreBresson** [comment]
Merci!
https://github.com/NMF-earth/nmf-app/pull/140#pullrequestreview-430373202
