### ISSUE TITLE
Images in the sustainable guide

### ISSUE THREAD

**Issue by PierreBresson** [NMF-earth/nmf-app#56]
Any markdown item (recipe & advices) in the sustainable guide should be able to display an image. Maybe it's already the case, I haven't tried

**Comment by devanshujain95** [comment]
@PierreBresson Something in reference to this? I was seeing open issues and found this one. 
Else any other feature/issue I should take on?

**Comment by PierreBresson** [comment]
@devanshujain95 this could be a bit long but it would be really nice to have it. We worked a bit on it a long time ago but since then nothing. First, you could try to see if the previous work is still working by displaying the [Act tab again](https://github.com/NMF-earth/nmf-app/blob/8728af885c855e7e34c081108e3e482d8e73abd1/app/navigation/Navigator/BottomTabNavigator.tsx#L29). 

Theo managed to make the first step : markdown files were converted to html to be displayed, because there is no good markdown library for react native (we want to use markdown to make things simple for non developer).

As a start, it would be nice to have an image between the title and the paragraph, for example :
![act-habits-technology-item](https://user-images.githubusercontent.com/8709134/84819087-c25f8e00-b017-11ea-9884-ca3529905a88.png)

**Comment by devanshujain95** [comment]
@PierreBresson Check [PR](https://github.com/NMF-earth/nmf-app/pull/142): 
The PR helps to even have multiple images in a markdown file. Then when rendered, these images are placed sequentially. Have a look.

<img width="319" alt="Screenshot 2020-06-19 at 12 13 58 AM" src="https://user-images.githubusercontent.com/17475986/85063619-06919080-b1c8-11ea-9848-24fae1f7be84.png">

**Comment by PierreBresson** [comment]
@devanshujain95 well done, I've merged it, thanks 🤗
