### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by ghost** [NMF-earth/nmf-app#96]
On iOS, app is too fat (100 MB) and on Android it could be lower (50 MB). Maybe tree shaking is not enabled

**Comment by theolampert** [comment]
This is probably not possible without ejecting from the managed workflow.

**Comment by PierreBresson** [comment]
To read : 
https://medium.com/@aswinmohanme/how-i-reduced-the-size-of-my-react-native-app-by-86-27be72bba640
https://stackoverflow.com/questions/49993006/how-to-reduce-the-size-of-an-expo-react-native-app-on-android#49993209

**Comment by PierreBresson** [comment]
Cannot do anything as long as we are in managed flow with expo
